### ISSUE TITLE
presto on k8s seems cannot talk to each other when the coordinator and worker in different k8s node?

### ISSUE THREAD

**Issue by zhaohhit** [prestosql/presto#4777]
hi ,
    I  install presto on k8s, and i find only when presto coordinator and work  on the same k8s node，i can run sql on presto, and everything is going well.but when  they on different node, the sql get stuck.

Here is my enviroment:

 I have three  ubuntu 16.04  virtual machine, and set up k8s cluster on them  by using kubeadm, and the network add-on is calico.

Here is the nodes info: 
![image](https://user-images.githubusercontent.com/52195388/89863354-82aec000-dbdc-11ea-8913-e6b4266667ee.png)

Here is the version of k8s cluster:
![image](https://user-images.githubusercontent.com/52195388/89863570-ea650b00-dbdc-11ea-9762-cb34e2e4e557.png)

As for presto,  i follow this project, and delete the s3 and hive config, add mysql.properties.
>https://github.com/uprush/kube-presto

Here is my docker file 

```
FROM openjdk:11-slim

# Variables that define which software versions to install.
ARG PRESTO_VERSION=330
ENV JAVA_HOME=/usr/local/openjdk-11

# Install dependencies
RUN apt-get update && apt-get install -y curl python --no-install-recommends

# Download and extract Presto server binary package.
RUN curl https://repo1.maven.org/maven2/io/prestosql/presto-server/$PRESTO_VERSION/presto-server-$PRESTO_VERSION.tar.gz \
	| tar xvz -C /opt/  \
	&& ln -s /opt/presto-server-$PRESTO_VERSION /opt/presto-server \
	&& mkdir -p /opt/presto-server/etc \
	&& mkdir -p /opt/presto-server/etc/catalog \
	&& mkdir -p /var/presto/data

ENV PRESTO_HOME="/opt/presto-server"

# Minimum config
COPY node.properties $PRESTO_HOME/etc

# Entry point
COPY entrypoint.sh /opt
ENTRYPOINT ["/opt/entrypoint.sh"]
```
 and the entrypoint.sh 

```
#!/bin/bash

set -e

# Each node needs to have different node.id
echo "node.id=$HOSTNAME" >> $PRESTO_HOME/etc/node.properties

/opt/presto-server/bin/launcher run
```

and the rest config file will be mounted into the container .

Here is the presto-server.yaml
```
---
apiVersion: v1
kind: Service
metadata:
  name: presto
  namespace: default
spec:
  type: NodePort
  selector:
    app: presto-coordinator
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: presto-coordinator
  namespace: default
spec:
  selector:
    matchLabels:
      app: presto-coordinator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: presto-coordinator
    spec:
      containers:
      - name: presto-coordinator
        image: itszhaohong/prestosql-server:330
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: presto-etc-vol
          mountPath: /opt/presto-server/etc/config.properties
          subPath: config.properties.coordinator
        - name: presto-etc-vol
          mountPath: /opt/presto-server/etc/jvm.config
          subPath: jvm.config.coordinator
        - name: presto-etc-vol
          mountPath: /opt/presto-server/etc/log.properties
          subPath: log.properties
        - name: presto-catalog-vol
          subPath: mysql.properties
          mountPath: /opt/presto-server/etc/catalog/mysql.properties
        resources:
          requests:
            memory: "2G"
            cpu: 1
          limits:
            memory: "32G"
            cpu: 8
        imagePullPolicy: Always
      volumes:
        - name: presto-etc-vol
          configMap:
            name: presto-etc
        - name: presto-catalog-vol
          configMap:
            name: presto-catalog

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: presto-worker
  namespace: default
spec:
  replicas: 2

  selector:
    matchLabels:
      app: presto-worker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: presto-worker
    spec:
      containers:
      - name: presto-worker
        image: itszhaohong/prestosql-server:330
        volumeMounts:
        - name: presto-etc-vol
          mountPath: /opt/presto-server/etc/config.properties
          subPath: config.properties.worker
        - name: presto-etc-vol
          mountPath: /opt/presto-server/etc/jvm.config
          subPath: jvm.config.worker
        - name: presto-etc-vol
          mountPath: /opt/presto-server/etc/log.properties
          subPath: log.properties
        - name: presto-catalog-vol
          subPath: mysql.properties
          mountPath: /opt/presto-server/etc/catalog/mysql.properties
        resources:
          requests:
            memory: "2G"
            cpu: 1
          limits:
            memory: "32G"
            cpu: 8
        imagePullPolicy: Always
      volumes:
        - name: presto-etc-vol
          configMap:
            name: presto-etc
        - name: presto-catalog-vol
          configMap:
            name: presto-catalog

```
Here is the configmap info
![image](https://user-images.githubusercontent.com/52195388/89865335-1c2ba100-dbe0-11ea-8616-4f304ef33f15.png)

![image](https://user-images.githubusercontent.com/52195388/89865314-13d36600-dbe0-11ea-82a8-6181e4befbcb.png)

![image](https://user-images.githubusercontent.com/52195388/89865281-05854a00-dbe0-11ea-92c6-dee2e6017e8f.png)

I deploy a mysql database on k8s cluster. 
Here is the config.
```
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: default
spec:
  type: NodePort
  selector:
    catalog: mysql
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 30336


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      catalog: mysql
  template:
    metadata:
      labels:
        catalog: mysql
    spec:
      containers:
      - name: mysql-container
        image: mysql/mysql-server:8.0

```

Since  all of them can run sql on one node of k8s cluster( because the k8s master  defaultly has traints, so pod will not be scheduled on k8s master), i don't think this depolyments has something wrong. It should be the network issue of k8s cluster. 

But i bash into the presto coordinator pod,i can ping the  presto worker by its pod ip.
And from the web ui , all workers have registered and are being alive.
![image](https://user-images.githubusercontent.com/52195388/89866241-c9eb7f80-dbe1-11ea-95aa-e2c256302ce7.png)

So, it seems the network has no problem.

------

When they in different nodes of k8s cluster ,the sql always get stuck in about 95% ,and 5 min later , it is gone.

Here is the WebUI stackTrace info,
![image](https://user-images.githubusercontent.com/52195388/89866138-9c9ed180-dbe1-11ea-99d8-6bea1403e69c.png)

```

io.prestosql.spi.PrestoTransportException: Encountered too many errors talking to a worker node. The node may have crashed or be under too much load. This is probably a transient issue, so please retry your query in a few minutes. (updating task http://192.168.35.65:8080/v1/task/20200811_035916_00026_sfqj4.1.0 - 30 failures, failure duration 302.91s, total failed request time 300.03s)
	at io.prestosql.server.remotetask.RequestErrorTracker.requestFailed(RequestErrorTracker.java:131)
	at io.prestosql.server.remotetask.HttpRemoteTask$UpdateResponseHandler.failed(HttpRemoteTask.java:802)
	at io.prestosql.server.remotetask.SimpleHttpResponseHandler.onFailure(SimpleHttpResponseHandler.java:85)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1052)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
	Suppressed: java.lang.RuntimeException: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed
		at io.airlift.http.client.ResponseHandlerUtils.propagate(ResponseHandlerUtils.java:24)
		at io.airlift.http.client.FullJsonResponseHandler.handleException(FullJsonResponseHandler.java:58)
		at io.airlift.http.client.FullJsonResponseHandler.handleException(FullJsonResponseHandler.java:38)
		at io.airlift.http.client.jetty.JettyResponseFuture.failed(JettyResponseFuture.java:120)
		at io.airlift.http.client.jetty.BufferingResponseListener.onComplete(BufferingResponseListener.java:85)
		at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:218)
		at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:210)
		at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:543)
		at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:523)
		at org.eclipse.jetty.client.HttpReceiver.abort(HttpReceiver.java:617)
		at org.eclipse.jetty.client.HttpChannel.abortResponse(HttpChannel.java:156)
		at org.eclipse.jetty.client.HttpChannel.abort(HttpChannel.java:149)
		at org.eclipse.jetty.client.HttpExchange.abort(HttpExchange.java:257)
		at org.eclipse.jetty.client.HttpConversation.abort(HttpConversation.java:149)
		at org.eclipse.jetty.client.HttpRequest.abort(HttpRequest.java:796)
		at org.eclipse.jetty.client.TimeoutCompleteListener.onTimeoutExpired(TimeoutCompleteListener.java:51)
		at org.eclipse.jetty.io.CyclicTimeout$Wakeup.run(CyclicTimeout.java:282)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
		... 3 more
	Caused by: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed
		... 8 more
```

The coordinator logs show that
>2020-08-11T04:02:13.387Z	WARN	UpdateResponseHandler-20200811_035916_00026_sfqj4.1.0-1245	io.prestosql.server.remotetask.RequestErrorTracker	Error updating task 20200811_035916_00026_sfqj4.1.0: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed: http://192.168.35.65:8080/v1/task/20200811_035916_00026_sfqj4.1.0
2020-08-11T04:02:16.281Z	WARN	TaskInfoFetcher-20200811_035916_00026_sfqj4.1.0-1246	io.prestosql.server.remotetask.RequestErrorTracker	Error getting info for task 20200811_035916_00026_sfqj4.1.0: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed: http://192.168.35.65:8080/v1/task/20200811_035916_00026_sfqj4.1.0
2020-08-11T04:02:23.889Z	WARN	UpdateResponseHandler-20200811_035916_00026_sfqj4.1.0-1245	io.prestosql.server.remotetask.RequestErrorTracker	Error updating task 20200811_035916_00026_sfqj4.1.0: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed: http://192.168.35.65:8080/v1/task/20200811_035916_00026_sfqj4.1.0

and the worker on 192.168.35.65 logs show that
>2020-08-11T04:04:10.240Z	WARN	http-worker-111	org.eclipse.jetty.util.SharedBlockingCallback	Blocker not complete Blocker@636991bf{null}
2020-08-11T04:04:10.241Z	WARN	http-worker-111	org.eclipse.jetty.util.thread.strategy.EatWhatYouKill	
java.lang.NullPointerException
	at io.airlift.http.server.HttpServerChannelListener.onRequestEnd(HttpServerChannelListener.java:62)
	at io.airlift.http.server.HttpServerChannelListener.onResponseBegin(HttpServerChannelListener.java:70)
	at org.eclipse.jetty.server.HttpChannelListeners.onResponseBegin(HttpChannelListeners.java:187)
	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:814)
	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:842)
	at org.eclipse.jetty.server.HttpChannel.onBadMessage(HttpChannel.java:775)
	at org.eclipse.jetty.server.HttpChannelOverHttp.badMessage(HttpChannelOverHttp.java:283)
	at org.eclipse.jetty.http.HttpParser.badMessage(HttpParser.java:1628)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1610)
	at org.eclipse.jetty.server.HttpConnection.parseRequestBuffer(HttpConnection.java:361)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:388)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.base/java.lang.Thread.run(Thread.java:834)

I try to google with those log info, but cannot fixed it.
I am new to k8s and presto, i don't know where is wrong.
Any suggestion will be appreciated.
